name: 'Check Regressions'

on:
  workflow_dispatch:
    inputs:
      versions:
        required: true
        type: string
        default: 'v18,v20,v21,v22,v23'
        description: 'The Node.js Versions (the folder must exist)'
      major-only:
        required: true
        type: boolean
        default: false
        description: 'Flag to check regression only between major versions'
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 'v22.x'

      - name: NPM Install
        run: npm install

      - name: Run Checker
        env:
          MAJOR_ONLY: ${{ inputs.major-only }}
          VERSIONS: ${{ inputs.versions }}
        run: node scripts/check-regression.mjs
